# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat", "Rcpp", "RcppArmadillo", "shiny", "jpeg", "png", "tiff", "utils", "covr"))'

r:
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = c("R/RcppExports.R", "src/RcppExports.cpp"), quiet = FALSE)'
  
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
