language: r
# warnings_are_errors: true
sudo: required

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

script:
  - ./travis-tool.sh run_tests

install:
  - ./travis-tool.sh install_aptget r-cran-runit
  - ./travis-tool.sh install_r Rcpp RcppArmadillo devtools roxygen2 testthat knitr rmarkdown grid shiny jpeg png tiff utils covr

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = c("R/RcppExports.R", "src/RcppExports.cpp"), quiet = FALSE)'
  
after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
